server:
  port: 8083

spring:
  application:
    name: CustomerService

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # database connection to postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: springuser
    password: springpass
    driver-class-name: org.postgresql.Driver


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: false

  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000